"use strict";
(async function(){
const $=s=>document.querySelector(s), mk=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
const db=await new Promise((ok,no)=>{const q=indexedDB.open('minha-agenda-v2',1);q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)});
const all=store=>new Promise((ok,no)=>{const q=db.transaction(store).objectStore(store).getAll();q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)});
const save=(store,v)=>new Promise((ok,no)=>{const q=db.transaction(store,'readwrite').objectStore(store).put(v);q.onsuccess=()=>ok();q.onerror=()=>no(q.error)});
const remove=(store,k)=>new Promise((ok,no)=>{const q=db.transaction(store,'readwrite').objectStore(store).delete(k);q.onsuccess=()=>ok();q.onerror=()=>no(q.error)});
const uuid=()=>crypto.randomUUID(),date=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const panel=$('#extras');if(!panel)return;
function section(name,html){const a=document.createElement('article');a.className='card';a.innerHTML='<h3>'+name+'</h3>'+html;panel.append(a);return a}
function notice(node,msg){node.querySelector('.notice').textContent=msg}
const physical=section('Evolução física','<form id="physical-form" class="v3form"><label>Data<input type="date" name="date" required></label><label>Peso (kg)<input type="number" step="0.1" min="1" max="500" name="weight" required></label><label>Cintura (cm, opcional)<input type="number" step="0.1" min="1" max="300" name="waist"></label><label>Observação<input name="note" maxlength="160"></label><button>Registrar medida</button></form><div id="physical-list"></div><p class="notice" role="status"></p>');
const timer=section('Cronômetro de treinos','<p id="rest-display" class="clock" aria-live="off">01:30</p><label>Descanso (segundos)<input id="rest-seconds" type="number" min="10" max="1800" value="90"></label><div class="actions"><button id="rest-start">Iniciar</button><button id="rest-pause">Pausar</button><button id="rest-reset">Reiniciar</button></div><p class="muted">O cronômetro funciona enquanto esta página estiver ativa.</p>');
const consistency=section('Calendário de consistência','<label>Mês<input id="consistency-month" type="month"></label><div id="consistency-grid" class="month-grid"></div><p class="muted">Dias com treinos ou estudos registrados. Descanso não é falha.</p>');
const cards=section('Flashcards de inglês','<form id="card-form" class="v3form"><label>Palavra ou expressão em inglês<input name="front" maxlength="120" required></label><label>Tradução / resposta<input name="back" maxlength="240" required></label><button>Adicionar cartão</button></form><div id="card-review"></div><div id="card-list"></div><p class="notice" role="status"></p>');
const cnh=section('Simulados da CNH','<p class="muted">Questões demonstrativas para revisão, não oficiais. Confira sempre a legislação e o material atualizado do DETRAN.</p><div id="quiz"></div><div id="quiz-result"></div><button id="quiz-restart">Novo simulado</button>');
const pomodoro=section('Modo foco / Pomodoro','<p id="focus-display" class="clock">25:00</p><label>Minutos por sessão<input id="focus-minutes" type="number" min="1" max="120" value="25"></label><label>Área<select id="focus-area"><option>Faculdade</option><option>Inglês</option><option>CNH</option></select></label><div class="actions"><button id="focus-start">Iniciar</button><button id="focus-pause">Pausar</button><button id="focus-reset">Reiniciar</button><button id="focus-save">Salvar sessão concluída</button></div><p class="notice" role="status"></p>');
const tasks=section('Tarefas da faculdade','<form id="college-form" class="v3form"><label>Atividade<input name="title" maxlength="120" required></label><label>Disciplina<input name="subject" maxlength="100" required></label><label>Prazo<input type="date" name="due" required></label><button>Adicionar tarefa</button></form><div id="college-list"></div><p class="notice" role="status"></p>');
const theme=section('Aparência','<label>Tema<select id="theme-choice"><option value="system">Seguir sistema</option><option value="light">Claro</option><option value="dark">Escuro</option></select></label><p class="muted">Preferência salva neste dispositivo.</p>');
physical.querySelector('[name=date]').value=date();
consistency.querySelector('#consistency-month').value=date().slice(0,7);
function drawRows(host,rows,render){host.replaceChildren();if(!rows.length)host.append(mk('p','Nenhum registro ainda.'));rows.forEach(r=>{const row=mk('div');row.className='line v3-row';const desc=mk('span',render(r));const btn=mk('button','Excluir');btn.className='danger';btn.onclick=async()=>{if(!confirm('Excluir este registro?'))return;await remove('records',r.id);await redraw()};row.append(desc,btn);host.append(row)})}
async function redraw(){const r=await all('records');drawRows($('#physical-list'),r.filter(x=>x.type==='physical').sort((a,b)=>b.date.localeCompare(a.date)),x=>x.date+' • '+x.weight+' kg'+(x.waist?' • cintura '+x.waist+' cm':''));drawRows($('#card-list'),r.filter(x=>x.type==='flashcard'),x=>x.front+' → '+x.back);const college=r.filter(x=>x.type==='collegeTask').sort((a,b)=>a.due.localeCompare(b.due));const host=$('#college-list');host.replaceChildren();college.forEach(x=>{const row=mk('div');row.className='line v3-row';const label=mk('label');const check=mk('input');check.type='checkbox';check.checked=!!x.done;check.onchange=async()=>{x.done=check.checked;await save('records',x);await redraw()};label.append(check,document.createTextNode(' '+x.title+' • '+x.subject+' • '+x.due));const delBtn=mk('button','Excluir');delBtn.className='danger';delBtn.onclick=async()=>{await remove('records',x.id);await redraw()};row.append(label,delBtn);host.append(row)});if(!college.length)host.append(mk('p','Nenhuma tarefa cadastrada.'));const month=$('#consistency-month').value;const days=new Set(r.filter(x=>['workout','study'].includes(x.type)&&typeof x.date==='string'&&x.date.startsWith(month)).map(x=>x.date));const grid=$('#consistency-grid');grid.replaceChildren();if(/^\d{4}-\d{2}$/.test(month)){const [year,m]=month.split('-').map(Number);const count=new Date(year,m,0).getDate();for(let d=1;d<=count;d++){const day=month+'-'+String(d).padStart(2,'0');const cell=mk('span',String(d));cell.title=day+(days.has(day)?' • atividade registrada':'');cell.className=days.has(day)?'active-day':'';grid.append(cell)}}await drawCardReview(r)}
physical.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await save('records',{id:uuid(),type:'physical',date:f.date,weight:Number(f.weight),waist:f.waist?Number(f.waist):null,note:f.note});e.target.reset();e.target.elements.date.value=date();await redraw();notice(physical,'Medida registrada.')};
cards.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await save('records',{id:uuid(),type:'flashcard',front:f.front.trim(),back:f.back.trim(),due:date(),interval:0});e.target.reset();await redraw();notice(cards,'Cartão criado.')};
tasks.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));await save('records',{id:uuid(),type:'collegeTask',...f,done:false});e.target.reset();await redraw();notice(tasks,'Tarefa cadastrada.')};
$('#consistency-month').onchange=redraw;
async function drawCardReview(r){const host=$('#card-review');host.replaceChildren();const due=r.filter(x=>x.type==='flashcard'&&(!x.due||x.due<=date())).sort((a,b)=>(a.due||'').localeCompare(b.due||''));if(!due.length){host.append(mk('p','Nenhum cartão pendente de revisão.'));return}const item=due[0],p=mk('p',item.front),answer=mk('p');answer.hidden=true;answer.textContent=item.back;const reveal=mk('button','Mostrar resposta');reveal.onclick=()=>{answer.hidden=false;actions.hidden=false};const actions=mk('div');actions.className='actions';actions.hidden=true;for(const [label,days] of [['Rever amanhã',1],['Lembrei (3 dias)',3],['Fácil (7 dias)',7]]){const b=mk('button',label);b.onclick=async()=>{const d=new Date();d.setDate(d.getDate()+days);item.due=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');item.interval=days;await save('records',item);await redraw()};actions.append(b)}host.append(p,reveal,answer,actions)}
function countdown(display,secondsInput,start,pause,reset){let remaining=Number(secondsInput.value),deadline=0,interval=null;const fmt=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');const show=()=>display.textContent=fmt(remaining);const stop=()=>{clearInterval(interval);interval=null};const tick=()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));show();if(remaining===0)stop()};start.onclick=()=>{if(interval)return;if(remaining<=0)remaining=Number(secondsInput.value)*60*(secondsInput.id==='focus-minutes'?1:1/60);deadline=Date.now()+remaining*1000;interval=setInterval(tick,250);show()};pause.onclick=()=>{if(interval){tick();stop()}};reset.onclick=()=>{stop();remaining=Number(secondsInput.value)*(secondsInput.id==='focus-minutes'?60:1);show()};secondsInput.onchange=()=>{if(!interval)reset.click()};show();return()=>({remaining,running:!!interval,reset:()=>reset.click()})}
countdown($('#rest-display'),$('#rest-seconds'),$('#rest-start'),$('#rest-pause'),$('#rest-reset'));
const focusState=countdown($('#focus-display'),$('#focus-minutes'),$('#focus-start'),$('#focus-pause'),$('#focus-reset'));
$('#focus-save').onclick=async()=>{const state=focusState();if(state.remaining!==0||state.running){notice(pomodoro,'Conclua a sessão antes de salvar.');return}const minutes=Number($('#focus-minutes').value);await save('records',{id:uuid(),type:'study',date:date(),area:$('#focus-area').value,topic:'Sessão Pomodoro',minutes,questions:0,correct:0,notes:'Registrado no modo foco'});state.reset();notice(pomodoro,'Sessão salva no histórico de estudos.');if(typeof refresh==='function')await refresh();await redraw()};
let questionBank=[...(window.CNH_QUESTION_BANK||[]),...(window.CNH_ILLUSTRATED_BANK||[]),...(window.CNH_MOSAIC_BANK||[])];
const baseQuestionBank=[...questionBank];
function validateNationalBank(data){if(!data||!Array.isArray(data.questions)||data.questions.length<1||data.questions.length>2500)throw Error('Arquivo de questões incompatível');const ids=new Set();return data.questions.map(x=>{if(typeof x.id!=='string'||!/^BNQ-P[12]-M[1-4]-\d+$/.test(x.id)||ids.has(x.id)||typeof x.question!=='string'||!x.question.trim()||x.question.length>1200||typeof x.correctAnswer!=='string'||!x.correctAnswer.trim()||!Array.isArray(x.wrongAnswers)||x.wrongAnswers.length!==3||x.wrongAnswers.some(a=>typeof a!=='string'||!a.trim())||typeof x.explanation!=='string'||x.explanation.length>2500)throw Error('Questão inválida no arquivo');ids.add(x.id);const matchedPlate=(window.CNH_MOSAIC_BANK||[]).find(p=>p.sourceCode===x.plateCode);return {image:matchedPlate?.image||null,imageAlt:matchedPlate?'Representação esquemática da placa '+x.plateCode:undefined,id:x.id,category:x.module||'CNH',q:x.question,a:[x.correctAnswer,...x.wrongAnswers],correct:0,explanation:x.explanation,sourceTitle:'Banco Nacional de Questões — versão 1.0',sourceCode:x.plateCode||null,origin:'banco-nacional',difficulty:x.difficulty,sourcePart:x.part}})}

const quizControls=document.createElement('div');quizControls.className='cnh-controls';
quizControls.innerHTML='<label>Modo<select id="cnh-mode"><option value="all">Todas</option><option value="illustrated">Ilustradas</option><option value="mistakes">Revisar erros</option></select></label><label>Assunto<select id="cnh-category"><option value="all">Todos os assuntos</option></select></label><label>Quantidade<select id="cnh-size"><option value="5">5 questões</option><option value="10" selected>10 questões</option><option value="20">20 questões</option><option value="30">30 questões (simulado)</option><option value="100">Todas disponíveis</option></select></label><p id="cnh-progress" class="muted" role="status"></p>';
cnh.insertBefore(quizControls,cnh.querySelector('#quiz'));
const nationalImporter=mk('div');nationalImporter.className='cnh-controls';const nationalLabel=mk('label','Importar Banco Nacional de Questões (JSON)');const nationalFile=mk('input');nationalFile.type='file';nationalFile.accept='.json,application/json';nationalFile.setAttribute('aria-label','Importar banco nacional de questões em JSON');nationalLabel.append(nationalFile);const nationalStatus=mk('p','O banco nacional é opcional e fica salvo neste dispositivo, sem apagar seu histórico.');nationalStatus.className='muted';nationalStatus.setAttribute('role','status');nationalImporter.append(nationalLabel,nationalStatus);cnh.insertBefore(nationalImporter,quizControls);

const categorySelect=quizControls.querySelector('#cnh-category');
function populateCnhCategories(){const selected=categorySelect.value;categorySelect.replaceChildren();const allOption=mk('option','Todos os assuntos');allOption.value='all';categorySelect.append(allOption);[...new Set(questionBank.map(q=>q.category))].sort().forEach(category=>{const o=mk('option',category);o.value=category;categorySelect.append(o)});categorySelect.value=[...categorySelect.options].some(o=>o.value===selected)?selected:'all'}
populateCnhCategories();
async function loadNationalQuestions(){const stored=(await all('settings')).find(x=>x.key==='cnhNationalBankV1');if(stored?.value){const national=validateNationalBank(stored.value);questionBank=[...national,...baseQuestionBank];nationalStatus.textContent='Banco Nacional carregado: '+national.length+' questões, mais '+baseQuestionBank.length+' questões anteriores.';populateCnhCategories()}}
nationalFile.onchange=async()=>{const file=nationalFile.files?.[0];if(!file)return;try{if(file.size>6_000_000)throw Error('Arquivo maior que 6 MB');const parsed=JSON.parse(await file.text());const national=validateNationalBank(parsed);await save('settings',{key:'cnhNationalBankV1',value:{source:parsed.source||'Banco Nacional de Questões — v1.0',questions:parsed.questions}});questionBank=[...national,...baseQuestionBank];populateCnhCategories();nationalStatus.textContent='Importadas '+national.length+' questões; histórico preservado. Faça backup da agenda para guardar este banco.';await startQuiz()}catch(err){nationalStatus.textContent='Não foi possível importar: '+err.message}finally{nationalFile.value=''}};

let questions=[],quizIndex=0,quizScore=0,quizMistakes=[],quizLocked=false,quizBreakdown={};let mistakeIds=[];const cnhStats=mk('div');cnhStats.className='cnh-stats';cnh.append(cnhStats);
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function renderCnhStats(){const records=(await all('records')).filter(r=>r.type==='study'&&r.area==='CNH'&&typeof r.topic==='string'&&r.topic.startsWith('Simulado CNH — '));cnhStats.replaceChildren();const title=mk('h4','Seu desempenho por assunto');cnhStats.append(title);if(!records.length){cnhStats.append(mk('p','Conclua um simulado para ver seu desempenho.'));return}const groups=new Map();for(const r of records){const breakdown=r.cnhBreakdown&&typeof r.cnhBreakdown==='object'?Object.entries(r.cnhBreakdown):[[r.topic.slice('Simulado CNH — '.length),{questions:r.questions,correct:r.correct}]];for(const [name,score] of breakdown){const item=groups.get(name)||{questions:0,correct:0,attempts:0};item.questions+=Math.max(0,Number(score.questions)||0);item.correct+=Math.max(0,Number(score.correct)||0);item.attempts++;groups.set(name,item)}}for(const [name,stats] of groups){const pct=Math.round(stats.correct/Math.max(1,stats.questions)*100);const row=mk('p',name+': '+pct+'% de acertos ('+stats.attempts+' simulado(s))');cnhStats.append(row)}}
async function startQuiz(){const mode=quizControls.querySelector('#cnh-mode').value;let pool=questionBank.filter(q=>categorySelect.value==='all'||q.category===categorySelect.value);if(mode==='illustrated')pool=pool.filter(q=>q.image);if(mode==='mistakes'){const records=await all('records');const missed=new Set(records.filter(r=>r.type==='study'&&r.area==='CNH').flatMap(r=>Array.isArray(r.cnhMistakeIds)?r.cnhMistakeIds:[]));pool=pool.filter(q=>missed.has(q.id))}questions=shuffle(pool).slice(0,Math.min(Number(quizControls.querySelector('#cnh-size').value),pool.length));quizIndex=0;quizScore=0;quizMistakes=[];mistakeIds=[];quizBreakdown={};quizLocked=false;$('#quiz-result').replaceChildren();renderQuiz()}
function renderQuiz(){const host=$('#quiz');host.replaceChildren();const progress=quizControls.querySelector('#cnh-progress');progress.textContent=questions.length?'Questão '+Math.min(quizIndex+1,questions.length)+' de '+questions.length+' · '+quizScore+' acertos':'Nenhuma questão disponível';
if(!questions.length){host.append(mk('p','Nenhuma questão encontrada. Escolha outro filtro ou conclua um simulado para registrar erros.'));return}if(quizIndex>=questions.length){host.append(mk('h4','Simulado concluído: '+quizScore+'/'+questions.length+' acertos ('+Math.round(quizScore/Math.max(1,questions.length)*100)+'%).'));if(quizMistakes.length){host.append(mk('h4','Revisar questões erradas'));quizMistakes.forEach(q=>{const p=mk('p',q.q+' — '+q.a[q.correct]);p.className='cnh-review';host.append(p)})}return}
const q=questions[quizIndex];if(q.image){const figure=mk('figure');figure.className='cnh-figure';const picture=mk('img');picture.src=q.image;picture.alt=q.imageAlt||'Ilustração educativa';picture.loading='lazy';figure.append(picture);host.append(figure)}host.append(mk('p',q.category+' · '+q.q));const feedback=mk('div');feedback.className='cnh-feedback';feedback.setAttribute('role','status');const next=mk('button',quizIndex===questions.length-1?'Concluir simulado':'Próxima questão');next.type='button';next.hidden=true;
q.a.forEach((option,i)=>{const b=mk('button',option);b.type='button';b.className='quiz-choice';b.onclick=()=>{if(quizLocked)return;quizLocked=true;const correct=i===q.correct;if(correct)quizScore++;else{quizMistakes.push(q);mistakeIds.push(q.id)}const category=quizBreakdown[q.category]||{questions:0,correct:0};category.questions++;if(correct)category.correct++;quizBreakdown[q.category]=category;host.querySelectorAll('.quiz-choice').forEach((choice,k)=>{choice.disabled=true;if(k===q.correct)choice.classList.add('cnh-correct');else if(k===i)choice.classList.add('cnh-wrong')});feedback.textContent=(correct?'Correto! ':'Resposta incorreta. ')+q.explanation;if(q.sourceUrl){const source=mk('a','Referência temática: '+q.sourceTitle);source.href=q.sourceUrl;source.target='_blank';source.rel='noopener noreferrer';feedback.append(mk('br'),source)}if(q.origin==='autoral')feedback.append(mk('p','Questão autoral, não oficial.','muted'));next.hidden=false};host.append(b)});
next.onclick=async()=>{if(!quizLocked)return;quizIndex++;quizLocked=false;if(quizIndex===questions.length){await save('records',{id:uuid(),type:'study',date:date(),area:'CNH',topic:'Simulado CNH — '+(categorySelect.value==='all'?'Geral':categorySelect.value),minutes:Math.max(1,questions.length),questions:questions.length,correct:quizScore,notes:'Questões educativas não oficiais',cnhBreakdown:quizBreakdown,cnhMistakeIds:mistakeIds});$('#quiz-result').textContent='Resultado salvo no histórico de estudos.';if(typeof refresh==='function')await refresh();await renderCnhStats()}renderQuiz()};host.append(feedback,next)}
$('#quiz-restart').onclick=()=>startQuiz().catch(console.error);categorySelect.onchange=()=>startQuiz().catch(console.error);quizControls.querySelector('#cnh-size').onchange=()=>startQuiz().catch(console.error);quizControls.querySelector('#cnh-mode').onchange=()=>startQuiz().catch(console.error);try{await loadNationalQuestions()}catch(err){nationalStatus.textContent='Banco salvo inválido: '+err.message}await startQuiz();await renderCnhStats();
const themeChoice=$('#theme-choice');const settings=await all('settings');themeChoice.value=settings.find(x=>x.key==='theme')?.value||'system';function applyTheme(){document.documentElement.dataset.theme=themeChoice.value}themeChoice.onchange=async()=>{applyTheme();await save('settings',{key:'theme',value:themeChoice.value})};applyTheme();await redraw();
})().catch(err=>{console.error('Agenda v3:',err);const n=document.querySelector('#extras');if(n)n.append(document.createTextNode('Erro ao carregar os recursos extras. Verifique o armazenamento do navegador.'))});
