"use strict";
/* Presentation only: does not alter IndexedDB, records, settings or backups. */
(()=>{const $=s=>document.querySelector(s),nav=document.querySelector('main > nav');if(!nav)return;
const mobile=document.createElement('nav');mobile.className='bottom-nav';mobile.setAttribute('aria-label','Navegação rápida');
const entries=[['inicio','⌂','Início'],['agenda','▦','Agenda'],['treinos','◉','Treinos'],['estudos','✎','Estudos'],['extras','✦','Extras']];
function select(page){const target=nav.querySelector('button[data-page="'+page+'"]');if(target)target.click();sync()}
function sync(){const active=nav.querySelector('button.active')?.dataset.page;mobile.querySelectorAll('button').forEach(b=>{const on=b.dataset.page===active;b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
for(const [page,icon,label] of entries){const b=document.createElement('button');b.type='button';b.dataset.page=page;b.setAttribute('aria-label',label);const glyph=document.createElement('span');glyph.textContent=icon;glyph.setAttribute('aria-hidden','true');b.append(glyph,document.createTextNode(label));b.addEventListener('click',()=>select(page));mobile.append(b)}
document.body.append(mobile);nav.addEventListener('click',()=>queueMicrotask(sync));sync();
const home=$('#inicio');if(home){const welcome=document.createElement('div');welcome.className='hero-welcome';const copy=document.createElement('div'),heading=document.createElement('strong'),subtitle=document.createElement('p');const h=new Date().getHours();heading.textContent=h<12?'Bom dia!':h<18?'Boa tarde!':'Boa noite!';subtitle.textContent='Seu progresso acontece um dia de cada vez.';copy.append(heading,subtitle);const mark=document.createElement('span');mark.className='hero-mark';mark.setAttribute('aria-hidden','true');mark.textContent='✦';welcome.append(copy,mark);const headingNode=home.querySelector('h2');if(headingNode)headingNode.after(welcome);const actions=document.createElement('div');actions.className='quick-actions';for(const [page,icon,label] of [['treinos','◉','Registrar treino'],['estudos','✎','Registrar estudo'],['progresso','↗','Ver progresso']]){const b=document.createElement('button');b.type='button';const i=document.createElement('span');i.textContent=icon;i.setAttribute('aria-hidden','true');b.append(i,document.createTextNode(label));b.addEventListener('click',()=>select(page));actions.append(b)}const stats=home.querySelector('#stats');if(stats)stats.after(actions)}
const extras=$('#extras');if(extras){const heading=extras.querySelector('h2');if(heading){heading.textContent='Suas ferramentas';const intro=document.createElement('p');intro.className='section-intro';intro.textContent='Treinos, foco, aprendizado e organização em um só lugar.';heading.after(intro)}}
})();
