"use strict";
(async()=>{
const $=s=>document.querySelector(s), node=(tag,txt,cls)=>{const e=document.createElement(tag);if(txt!==undefined)e.textContent=txt;if(cls)e.className=cls;return e};
const db=await new Promise((yes,no)=>{const q=indexedDB.open('minha-agenda-v2',1);q.onsuccess=()=>yes(q.result);q.onerror=()=>no(q.error)});
const all=store=>new Promise((yes,no)=>{const q=db.transaction(store).objectStore(store).getAll();q.onsuccess=()=>yes(q.result);q.onerror=()=>no(q.error)});
const put=(store,data)=>new Promise((yes,no)=>{const q=db.transaction(store,'readwrite').objectStore(store).put(data);q.onsuccess=()=>yes();q.onerror=()=>no(q.error)});
const del=(store,id)=>new Promise((yes,no)=>{const q=db.transaction(store,'readwrite').objectStore(store).delete(id);q.onsuccess=()=>yes();q.onerror=()=>no(q.error)});
const dateString=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const today=dateString(new Date());
const monthDays=ym=>{const [y,m]=ym.split('-').map(Number);return new Date(y,m,0).getDate()};
const parseDate=s=>new Date(Number(s.slice(0,4)),Number(s.slice(5,7))-1,Number(s.slice(8,10)));
const settings=await all('settings');const config=settings.find(s=>s.key==='dashboard41')?.value||{workouts:true,study:true,weight:true,upcoming:true};
const home=$('#inicio'),progress=$('#progresso'),agenda=$('#agenda');
if(!home||!progress||!agenda)return;
const dashboard=node('article',undefined,'card v41-dashboard'),heading=node('h3','Meu painel');dashboard.append(heading);
const opts=node('div',undefined,'v41-options');const optionNames={workouts:'Treinos',study:'Estudos',weight:'Peso corporal',upcoming:'Próximos prazos'};
Object.entries(optionNames).forEach(([key,label])=>{const l=node('label',undefined,'v41-toggle'),c=node('input');c.type='checkbox';c.checked=config[key]!==false;c.addEventListener('change',async()=>{config[key]=c.checked;await put('settings',{key:'dashboard41',value:config});await draw()});l.append(c,document.createTextNode(label));opts.append(l)});
const dashCards=node('div',undefined,'v41-summary');dashboard.append(opts,dashCards);home.querySelector('.quick-actions')?.after(dashboard);
if(!dashboard.isConnected)home.append(dashboard);
const chartBox=node('article',undefined,'card'),chartHeading=node('h3','Relatórios dos últimos 7 dias'),chartLegend=node('p','Cada barra representa um dia. Os minutos de estudo e os exercícios registrados são contabilizados separadamente.','muted'),chartHost=node('div',undefined,'v41-charts');chartBox.append(chartHeading,chartLegend,chartHost);progress.prepend(chartBox);
const calendar=node('article',undefined,'card'),calendarTitle=node('h3','Calendário mensal'),monthLabel=node('label','Selecione o mês'),monthInput=node('input');monthInput.type='month';monthInput.value=today.slice(0,7);monthLabel.append(monthInput);
const grid=node('div',undefined,'v41-calendar'),upcoming=node('div'),eventForm=node('form');eventForm.className='v41-event-form';eventForm.innerHTML='<h3>Novo compromisso</h3><label>Data<input type="date" name="date" required></label><label>Título<input name="title" required maxlength="120"></label><label>Categoria<select name="category"><option>Pessoal</option><option>Faculdade</option><option>Trabalho</option><option>Outro</option></select></label><button type="submit">Adicionar compromisso</button>';eventForm.elements.date.value=today;
calendar.append(calendarTitle,monthLabel,grid,node('h3','Compromissos e prazos'),upcoming,eventForm);agenda.append(calendar);
function drawBars(target,items,field){const max=Math.max(1,...items.map(x=>x[field]));const plot=node('div',undefined,'v41-bars');items.forEach(x=>{const column=node('div',undefined,'v41-column'),bar=node('div',undefined,'v41-bar'),value=node('strong',String(x[field])),label=node('small',x.date.slice(8));bar.style.height=Math.max(3,Math.round(x[field]/max*110))+'px';bar.title=x.date+': '+x[field];column.append(value,bar,label);plot.append(column)});target.append(plot)}
function addMetric(text){const card=node('div',text,'v41-metric');dashCards.append(card)}
function appendEntry(host,item,isEvent){const row=node('div',undefined,'v41-entry'),text=node('span',item.date+' · '+(isEvent?item.title:item.title+' ('+item.subject+')')),btn=node('button','Excluir','danger');btn.type='button';btn.addEventListener('click',async()=>{if(!confirm('Excluir este item?'))return;await del('records',item.id);await draw()});row.append(text,btn);host.append(row)}
async function draw(){const records=await all('records');const workouts=records.filter(r=>r.type==='workout'&&typeof r.date==='string'),studies=records.filter(r=>r.type==='study'&&typeof r.date==='string'),weights=records.filter(r=>r.type==='physical'&&Number.isFinite(Number(r.weight))&&typeof r.date==='string').sort((a,b)=>b.date.localeCompare(a.date));
const events=records.filter(r=>r.type==='event'&&typeof r.date==='string'),tasks=records.filter(r=>r.type==='collegeTask'&&!r.done&&typeof r.due==='string');
dashCards.replaceChildren();if(config.workouts!==false)addMetric('Treinos registrados: '+workouts.length);if(config.study!==false)addMetric('Estudo acumulado: '+studies.reduce((n,r)=>n+(Number(r.minutes)||0),0)+' min');if(config.weight!==false)addMetric('Último peso: '+(weights.length?weights[0].weight+' kg':'sem registro'));if(config.upcoming!==false)addMetric('Prazos futuros: '+(events.filter(r=>r.date>=today).length+tasks.filter(r=>r.due>=today).length));
const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-6+i);return{date:dateString(d),workouts:0,minutes:0}});days.forEach(day=>{day.workouts=workouts.filter(r=>r.date===day.date).length;day.minutes=studies.filter(r=>r.date===day.date).reduce((n,r)=>n+(Number(r.minutes)||0),0)});
chartHost.replaceChildren();[['Exercícios registrados','workouts'],['Minutos estudados','minutes']].forEach(([title,field])=>{const box=node('div'),h=node('h4',title);box.append(h);drawBars(box,days,field);chartHost.append(box)});
const ym=monthInput.value;if(!/^\d{4}-\d{2}$/.test(ym))return;grid.replaceChildren();const first=parseDate(ym+'-01').getDay();['D','S','T','Q','Q','S','S'].forEach(d=>grid.append(node('span',d,'v41-weekday')));for(let i=0;i<first;i++)grid.append(node('span','','v41-empty'));for(let i=1;i<=monthDays(ym);i++){const d=ym+'-'+String(i).padStart(2,'0');const count=events.filter(e=>e.date===d).length+tasks.filter(t=>t.due===d).length;const b=node('button',String(i)+(count?' •':''),count?'v41-day marked':'v41-day');b.type='button';b.title=d+(count?' · '+count+' compromisso(s)':'');b.setAttribute('aria-label',d+', '+count+' compromissos');b.onclick=()=>{eventForm.elements.date.value=d;eventForm.elements.title.focus()};grid.append(b)}
upcoming.replaceChildren();const sorted=[...events.map(x=>({...x,_event:true})),...tasks.map(x=>({...x,date:x.due,_event:false}))].filter(x=>x.date>=ym+'-01'&&x.date<=ym+'-'+String(monthDays(ym)).padStart(2,'0')).sort((a,b)=>a.date.localeCompare(b.date));if(!sorted.length)upcoming.append(node('p','Nenhum compromisso ou prazo neste mês.','muted'));sorted.forEach(x=>{if(x._event)appendEntry(upcoming,x,true);else{const row=node('p',x.date+' · '+x.title+' ('+x.subject+')','v41-entry');upcoming.append(row)}});
}
monthInput.addEventListener('change',draw);eventForm.addEventListener('submit',async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(eventForm));if(!/^\d{4}-\d{2}-\d{2}$/.test(f.date))return;await put('records',{id:crypto.randomUUID(),type:'event',date:f.date,title:f.title.trim(),category:f.category});eventForm.elements.title.value='';monthInput.value=f.date.slice(0,7);await draw()});
document.querySelectorAll('main > nav button').forEach(b=>b.addEventListener('click',()=>{if(['inicio','agenda','progresso'].includes(b.dataset.page))draw().catch(console.error)}));document.addEventListener('visibilitychange',()=>{if(!document.hidden)draw().catch(console.error)});await draw();
})().catch(e=>{console.error('Agenda 4.1:',e);const n=document.querySelector('#inicio');if(n)n.append(document.createTextNode('Os relatórios não puderam ser carregados. Os registros existentes não foram alterados.'))});
